#pragma once
#include "CoreMinimal.h"

#define BLOCK_SIZE 52
#define WALL_LENGTH 12
#define WALL_HEIGHT 25

#define GAME_OVER_HEIGHT 20

#define MOVE_DOWN_RATE 1.0f

#define UPCOMING_BLOCKS_NUMBER 4
#define UPCOMING_BLOCK_GAP 4

#define ROW_FILLED_SCORE 100
#define TWO_ROWS_FILLED_SCORE 250
#define THREE_ROWS_FILLED_SCORE 500
#define FOUR_ROWS_FILLED_SCORE 1000

